www:
  - packages/www/src/**/*
  - packages/www/public/**/*

blog:
  - packages/blog/src/**/*
  - packages/blog/public/**/*

post: packages/blog/posts/**/*

moment: packages/moment/src/**/*

chore:
  - "!packages/**/src/**/*"
  - "./**/*"

docs:
  - "docs/*"
  - "docs/**/*"
