www:
  - packages/www/src/**/*
  - packages/www/public/**/*

blog: packages/blog/posts/**/*

moment: packages/moment/src/**/*

chore:
  - "!packages/**/src/**/*"
  - "./**/*"

docs:
  - "docs/*"
  - "docs/**/*"
